### ISSUE TITLE
how to reset the position of conditions

### ISSUE THREAD

**Issue by onion5376** [povilaskarvelis/DataViz#1]
Recently, I try to use this toolbox to draw the boxplot graph, but a problem has been encountered. Sometimes, there is only two groups in one condition, so the gap between conditions is large. I try to reduce this gap to make a more beautiful graph. Though "daboxplot" have many output arguments including a parameter "cpos" for further customization, it can not work (like, set(h1.cpos,0.5:0.5:1.6)). Is another method used to control the position of conditions?

**Comment by povilaskarvelis** [comment]
You can reduce the gap between the groups by including 'boxspacing' variable when you run daboxplot: eg. daboxplot(data,'boxspacing',0.8). This will scale down the spacing between the groups (default value for 'boxspacing' is 1). Another option you might find useful is 'boxwidth', which allows to scale the size of the boxplots themselves (default is also 1). Please see the documentation at the top of the daboxplot script for more details. Let me know if that helps!

**Comment by onion5376** [comment]
Thanks for your reply. I try to follow your instructions, but it still seems unresolved. The options "boxspacing" and "boxwidth" affect the gaps between boxes in the same condition. As shown in the picture belowed, I want to reduce gaps between conditions. Could you give another adivice to solve it.

Best wish, onion.

**Comment by povilaskarvelis** [comment]
Increasing 'boxwidth' to higher values (e.g., 1.4), automatically results in less gaps between conditions, (the gaps in the same condition remain unchanged as they are scaled by the boxwidth).

**Comment by onion5376** [comment]
Following your instruction, the gap between conditions can be reduce by increasing value of the 'boxwidth'. It means that there is an inverse relationship between  the gap size and box size. Sometimes, we want the size of box to be constant and make the small gap between conditions. Maybe this tool could not meet this requirement. Thank you all the same.

Best wish, onion.

**Comment by povilaskarvelis** [comment]
The result you desire could be achieved by reducing the plot size (in combination with increasing the boxwidth). But thank you for your feedback, I will think about how to make such modifications easier in the future.
