### ISSUE TITLE
A tiny plotting bug in daviolinplot.m file.

### ISSUE THREAD

**Issue by ZCSHEN98** [povilaskarvelis/DataViz#3]
Hello, I found a tiny bug when I tried to set different numbers of 'outfactor' to show different results but there was no change of anything.
I searched where is wrong in the code and I think the bug is caused by the code on line 446 in the file 'daviolinplot.m':
ox = data_vals<(pt(3,k)-IQR(k)) |  data_vals>(pt(5,k)+IQR(k));
I modified it as follows:
ox = data_vals<(pt(3,k)-confs.outfactor * IQR(k)) |  data_vals>(pt(5,k)+confs.outfactor * IQR(k));
Then it works.
I hope I corrected the code and no other bug about this 'outfactor' function.
Thanks.

Sincerely,
User

**Comment by povilaskarvelis** [comment]
Thank you! I very much appreciate spotting this bug! It seems that
previously I only implemented confs.outfactor for calculating the length of
whiskers, but not the outliers themselves. Thanks again!
