### ISSUE TITLE
Missing values

### ISSUE THREAD

**Issue by krib-ula** [povilaskarvelis/DataViz#4]
Hi there, I'm wondering if you know of a good way to skip missing values, or how to plot data of different lengths in matrices using the daviolinplot function. I have a few missing data points and can either treat them as nan or 0 - nan results in an error, and 0 will skew the violin plots. 

Thanks in advance for any help you can provide! :)

**Comment by povilaskarvelis** [comment]
The code should support NaNs. What error do you get with NaNs?

**Comment by krib-ula** [comment]
You're right! It was a mistake on my end. Thank you
