### ISSUE TITLE
Needs statistical toolbox

### ISSUE THREAD

**Issue by jankap** [povilaskarvelis/DataViz#6]
Seems to be a very nice visualization tool. Unfortunately, it needs the Statistics and Machine Learning Toolbox I don't have licensed. 

At a first glance I see `grp2idx` which is not available. Is there any chance to work-around that call with `findgroups` https://www.mathworks.com/help/matlab/ref/findgroups.html?

edit: Neither the Matlab File Exchange nor the repo states that the toolbox is needed, it might make sense to update the docs accordingly :)

**Comment by povilaskarvelis** [comment]
Thank you for the suggestion! The dependency on the statistics and ml toolbox has now been removed :)
