### ISSUE TITLE
inputParser() uses positional arguments

### ISSUE THREAD

**Issue by elmarplischke** [povilaskarvelis/DataViz#7]
While porting the code to octave (almost works, except that legend picks up the wrong colors, and marker sizes are a bit too big) I noticed that the 
`p=inputParser() `
uses
`addOptional(p,'bla','blubb')`
however, it seems that this should be foremost used for positional arguments. Key/value pairs should use `addParameter()`

In the violin plot, octave therefore set `confs.groups` to "groups" and `confs.violin` to to the group list, which ended with box_xcor being uninitialized. Matlab's parser seems to be a bit more flexible.

**Comment by povilaskarvelis** [comment]
Thanks for pointing this out. It has been fixed now
